### ISSUE TITLE
Server crash (null pointer) durring multi-block tank assimilate

### ISSUE THREAD

**Issue by glasspelican** [Drayshak/EnderTech#33]
server log filtered for messages from endertech
http://termbin.com/v08d

crashlog
http://termbin.com/wdvo

affected line = 297
https://github.com/Drayshak/EnderTech/blob/31b64aa55529df1a5fa8a6941546898001c64deb/src/main/java/io/endertech/multiblock/controller/ControllerTank.java#L297
http://screenshot.glasspelican.ca/E7gY

issue appears to still exist in current version of file line 300

**Comment by Drayshak** [comment]
As far as I can tell this is already fixed? https://github.com/Drayshak/EnderTech/blob/master/src/main/java/io/endertech/multiblock/controller/ControllerTank.java#L293

The problem before was that the candidate was getting set after I printed a debug line, rather than before. Now it should be set so the candidate.toString is safe.

**Comment by Drayshak** [comment]
Indeed, I double checked and build 360 fixed this. Please update to the latest version (at the time of writing, build 364).

**Comment by glasspelican** [comment]
its the firepack.
im going to grab an affected backup of fires sub-server and try the newer build

**Comment by Yorkforce** [comment]
Sky Factory 2 has version 358 and this is occurring on servers, please poke bacon_donut :)

**Comment by Drayshak** [comment]
I'm going to close this as I've poked the right people - it's up to them to update.
